dist: xenial

language: python
python:
  - 3.8

env:
  global:
    # Doctr deploy key for keurfonluu/stochopy
    - secure: "SSH6M8oo3T4DRDZwbn4PSh4cl5KhkORJefuDOhuCCfV5/OO4CVvFbEuqSRlFlyh/0hpuZKbmXHb5jz6eRBcqW+XIC8ct19cdJvcK9OXVO4XzP4s6Hdse2s6gCh58+WjBMwt2Y16pu/YvgpnTD9J11azKP26oFfqQ4RMxiNP47TY//tHOi7x+mvtfME7wlO49U/iY3dmnJMHteHZG2WejUs3uxc759yue44bMMeWAkeXiyEdFmS8p8VYkEBfBaIwcYHrChGDtoiwGeXo3Ati6Ct/DFS2CDMwsscTA9A7RnTN+gROkeTtAWbNzPUEl/5XcK4uugrrltAoZ5FiJOWry5Y/SImI/Lv+H86ba82Yk4y2UwUql3L6khiadJDb9f1Jcd42nIjfb6CqzbDwt0JGRo053DZVH8g172OLL5NZo6iaJMCijNX8q0Dz/xtyujm4ett6sCtP8HtsRIIFemEfr7mmXd+Shs7HI0BzvN7uisrwjj7QZwCx1xL7sX8eSj1l3FfL+0WgisdoBIKe2+2N3lLyRMZZVsh70M3eYpJV5jUSDXaX8r28JrBsER+vZz45xxLe7w2mxui3WeKlzmFBcoHgtO/IPqQZ6EFPi5UICxcEVbmpGyuIKHcweVurcbkQKAuo1A2uuEzevqKSaS6zJ/qCsOMZDKSY9awqjMEecRH0="

install:
  - pip install .
  - pip install -r doc/requirements.txt

script:
  - set -e
  - sphinx-build -b html doc/source doc/build
  - pip install doctr
  - doctr deploy . --built-docs ./doc/build/